### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by FDiskas** [niborb/react-native-gravatar#3]
```
Module parse failed: /node_modules/react-native-avatar-gravatar/index.js Unexpected token (29:16)
You may need an appropriate loader to handle this file type.
```

**Comment by niborb** [comment]
The code uses ES2015 destructuring. 
You need the [babel](https://babeljs.io/) transpiler to compile it to ES5.

Can you explain how you get this error with the React Native package builder?

**Comment by FDiskas** [comment]
I did it wrong. I was trying to use this plugin in web project with webpack. Did't noticed about "react-native..." in the title of your work.
